spring:
  application:
    name: GelatoFlow
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/gelatoflow
    username: postgres
    password: 9844
  jpa:
    database: POSTGRESQL
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: FLYWAY_HISTORY_GELATOFLOW
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    username: postgres
    password: 9844