spring:
  application:
    name: GelatoFlow
  config:
    import: environment.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/gelatoflow
    username: postgres
    password: 9844
  jpa:
    database: POSTGRESQL
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: FLYWAY_HISTORY_GELATOFLOW
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    username: postgres
    password: 9844
  logging:
    config: classpath:log4j2-spring.xml

jwt:
  secret: "${environment.jwt.secret:default-secret}"
  expiration: "${environment.jwt.expiration:3600}"